title: Journo Type
description: This website contains my blog featuring articles about fonts
  throughout journalism
header_text: Journo Type
footer_text: Copyright 2020 Lucyanna Paluk
header_feature_image: ../uploads/pages.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
