title: Journo Type
description: This website contains my blog featuring articles about fonts
  throughout journalism
header_text: "The Media: how the typography conveys a story"
footer_text: Copyright 2020 Lucyanna Paluk
header_feature_image: ../uploads/bruno-martins-ohjmwb4xwle-unsplash.jpg
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
