title: Journo Type
description: This website contains my blog featuring articles about fonts
  throughout journalism
header_text: ""
footer_text: Copyright 2020 Lucyanna Paluk
header_feature_image: ../uploads/the-fonts-that-tell-a-story.-2.png
bannerheight: 20vmax
logo: ../uploads/journo-type-logo.png
favicon: ../uploads/favicon-16x16.png
gridlayout: false
fixednavbar: false
upzoom: true
